### ISSUE TITLE
Didn't include oh-my-zsh file in the repo

### ISSUE THREAD

**Issue by elitelinuxuser** [Conor-Burns/dotfiles#2]
Hey I am loving your theme. It would be great if you could share your oh-my-zsh file

**Comment by Conor-Burns** [comment]
This is intended, as it would break the auto update of oh my zsh, because it is a git repo in itself.
BTW there is no configuration stored in oh my zsh. It is all in the .zshrc. 
all you have to do is run this `sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`

**Comment by Conor-Burns** [comment]
closed for inactivity - reopen if needed
